version: '3.7'

services:
    flask:
        container_name: crashhub
        build:
            context: ../src
            dockerfile: $PWD/Crashhub/Dockerfile
            args:
                - appName
                - githubProject
                - githubToken
                - postgresUser
                - postgresPassword
                - postgresDatabase
        volumes:
            - "./Crashhub/entrypoint.sh:/app/entrypoint.sh"
        environment:
            - FLASK_APP=/app/crashhub.py
        expose:
            - 5000
        depends_on:
            - postgres
        networks:
            - crashhub
    postgres:
        container_name: db_crashhub
        image: postgres:11.4
        volumes:
            - crashhub_db:/var/lib/postgresql/data
        environment:
            - "POSTGRES_USER:${postgresUser}"
            - "POSTGRES_PASSWORD:${postgresPassword}"
            - "POSTGRES_DB:${postgresDatabase}"
        expose:
            - 5432
        networks:
            - crashhub
volumes:
        crashhub_db:
networks:
        crashhub:
