version: '3.7'

services:
    crashhub:
        build:
            context: ../
            dockerfile: $PWD/Crashhub/Dockerfile
            args:
                - appName
                - githubProject
                - githubToken
                - dbEngine
                - dbHost
                - dbPort
                - postgresUser
                - postgresPassword
                - postgresDatabase
        network_mode: host
        ports:
            - "${CRASHHUB_SERVICE_PORT}:8081"
        depends_on:
            - postgres
            - nginxSSL
    postgres:
        image: postgres:11.4
        network_mode: host
        volumes:
            - crashhub_db:/var/lib/postgresql/data
        environment:
            - "POSTGRES_USER:${postgresUser}"
            - "POSTGRES_PASSWORD:${postgresPassword}"
            - "POSTGRES_DB:${postgresDatabase}"
        ports:
            - "${CRASHHUB_DB_PORT}:5432"
    nginx:
        image: nginx:latest
        network_mode: host
        ports:
            - "80:80"
        volumes:
            - "./Nginx/Crashhub.template:/etc/nginx/conf.d/Crashhub.template"
            - "web-root:/var/www/html"
        command: /bin/bash -c "cat /etc/nginx/conf.d/Crashhub.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    nginxSSL:
        image: nginx:latest
        network_mode: host
        ports:
            - "443:443"
        volumes:
            - "./Nginx/entrypoint.sh:/app/entrypoint.sh"
            - "./Nginx/CrashhubSSL.template:/etc/nginx/conf.d/CrashhubSSL.template"
            - "/var/log/nginx/:/var/log/nginx/"
            - "certbot-etc:/etc/letsencrypt"
            - "certbot-var:/var/lib/letsencrypt"
        environment:
            - NGINX_HOST=${serverName}
        restart: always
        depends_on:
            - certbot
        command: /bin/sh -c /app/entrypoint.sh 
    certbot:
        image: certbot/certbot
        volumes:
            - "./Certbot/entrypoint.sh:/app/entrypoint.sh"
            - "certbot-etc:/etc/letsencrypt"
            - "certbot-var:/var/lib/letsencrypt"
            - "web-root:/var/www/html"
        environment:
            - CONTACT_EMAIL=$contactEmail
            - CERT_DOMAINS=$certDomains
        depends_on:
            - nginx
        entrypoint: /bin/sh -c /app/entrypoint.sh
volumes:
        crashhub_db:
        certbot-etc:
        certbot-var:
        web-root:
